version: '3'

services:
    app:
        build:
            context: ./node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node index.js
        networks:
            - node-network
        volumes:
            - ./node:/usr/src/app
            - /usr/src/app/node_modules
        tty: true
        depends_on:
            - mysql
        ports:
            - "3000:3000"

    mysql:
        build:
            context: ./mysql
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        environment: 
            - MYSQL_DATABASE=${DATABASE}
            - MYSQL_ROOT_PASSWORD=${PASSWORD}
        networks:
            - node-network
        ports:
            - "3306:3306"

    nginx:
        build:
            context: ./nginx
        image: javielrezende/nginx
        container_name: nginx
        depends_on:
            - app
        networks: 
            - node-network
        ports: 
            - "8080:80"

networks:
    node-network:
        driver: bridge
